# Generated by Django 2.2.12 on 2020-07-10 09:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('note', models.IntegerField()),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admisssion',
                'verbose_name_plural': 'Admisssions',
            },
        ),
        migrations.DeleteModel(
            name='Admisssion',
        ),
        migrations.AlterField(
            model_name='caracteristique',
            name='icone',
            field=models.CharField(choices=[('fa fa-school-material text-white', 'school-material text-white'), ('fa fa-mortarboard text-white', 'mortarboard text-white'), ('fa fa-library text-white', 'library text-white'), ('fa fa-school-material', 'school-material '), ('fa fa-mortarboard ', 'mortarboard '), ('fa fa-library ', 'library ')], max_length=255),
        ),
    ]
