# Generated by Django 2.2.12 on 2020-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0002_auto_20200710_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristique',
            name='icone',
            field=models.CharField(choices=[('flaticon-school-material', 'School'), ('flaticon-mortarboard', 'Mortarboard'), ('flaticon-library', 'Library')], max_length=255),
        ),
    ]
