# Generated by Django 2.2.12 on 2020-07-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0004_new_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
