# Generated by Django 2.2.12 on 2020-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0005_delete_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='titre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
