# Generated by Django 2.2.12 on 2020-07-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0006_video_titre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admission',
            new_name='Admisssion',
        ),
    ]
