# Generated by Django 2.2.12 on 2020-07-11 19:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0007_auto_20200711_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaine',
            name='content',
            field=tinymce.models.HTMLField(null='True', verbose_name='Content'),
            preserve_default='True',
        ),
    ]
