# Generated by Django 2.2.12 on 2020-07-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0008_domaine_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cour',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
