# Generated by Django 2.2.12 on 2020-07-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0009_cour_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cour',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
