# Generated by Django 2.2.12 on 2020-07-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0010_auto_20200712_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
