# Generated by Django 2.2.12 on 2020-07-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universite', '0011_auto_20200712_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
