# Generated by Django 2.2.12 on 2020-07-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/about')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logo/caracteristique')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caracteristique',
                'verbose_name_plural': 'Caracteristiques',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telephone', models.FloatField()),
                ('message', models.TextField()),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('matiere', models.CharField(max_length=255)),
                ('biographie', models.TextField()),
                ('photo', models.ImageField(upload_to='images/enseignant')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='Newletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newletter',
                'verbose_name_plural': 'Newletters',
            },
        ),
        migrations.CreateModel(
            name='Reseau_social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('lien', models.URLField()),
                ('icone', models.CharField(choices=[('fa fa-facebook', 'facebook'), ('fa fa-twitter', 'twitter'), ('fa fa-linkedin', 'linkedin')], max_length=255)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reseau_social',
                'verbose_name_plural': 'Reseau_sociaux',
            },
        ),
        migrations.CreateModel(
            name='Siteinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('telephone', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='images/logo')),
                ('caracteristique_bg', models.ImageField(upload_to='images/caracteristique')),
                ('newletter_bg', models.ImageField(upload_to='images/newletter')),
                ('newletter_title', models.CharField(max_length=255)),
                ('newletter_description', models.TextField()),
                ('copyrights', models.CharField(max_length=255)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Siteinfo',
                'verbose_name_plural': 'Siteinfos',
            },
        ),
        migrations.CreateModel(
            name='slice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/slice')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'slice',
                'verbose_name_plural': 'slices',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=255)),
                ('Temoignage', models.TextField()),
                ('photo', models.ImageField(upload_to='images/temoignage')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Temoignage',
                'verbose_name_plural': 'Temoignages',
            },
        ),
    ]
