# Generated by Django 2.2.12 on 2020-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='slogan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
