# Generated by Django 2.2.12 on 2020-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_siteinfo_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseau_social',
            name='icone',
            field=models.CharField(choices=[('icon-facebook', 'facebook'), ('icon-twitter', 'twitter'), ('icon-linkedin', 'linkedin')], max_length=255),
        ),
    ]
