# Generated by Django 2.2.12 on 2020-07-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200710_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristique',
            name='logo',
        ),
    ]
