# Generated by Django 2.2.12 on 2020-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_siteinfo_logo_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='description_footer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo_footer',
            field=models.ImageField(null=True, upload_to='images/logofooter'),
        ),
    ]
