# Generated by Django 2.2.12 on 2020-07-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200710_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slice',
            options={'verbose_name': 'Slice', 'verbose_name_plural': 'Slices'},
        ),
    ]
