# Generated by Django 2.2.12 on 2020-07-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_siteinfo_bg_autre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='bg_autre',
            field=models.ImageField(null='True', upload_to='images/autre'),
        ),
    ]
