# Generated by Django 2.2.12 on 2020-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200711_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description2',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
