# Generated by Django 2.2.12 on 2020-07-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_about_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='about_description',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='about_image',
            field=models.ImageField(null='True', upload_to='images/aboutsite'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='titre_about',
            field=models.CharField(max_length=255, null='True'),
            preserve_default='True',
        ),
    ]
