# Generated by Django 2.2.12 on 2020-07-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200711_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='login_description',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='register_description',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
