# Generated by Django 2.2.12 on 2020-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200711_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='contact_description',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
