# Generated by Django 2.2.12 on 2020-07-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_siteinfo_contact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description2', models.TextField()),
                ('image', models.ImageField(upload_to='image/aboutt')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aboutt',
                'verbose_name_plural': 'Aboutts',
            },
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
