# Generated by Django 2.2.12 on 2020-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_siteinfo_admission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='admission_description',
            field=models.TextField(),
        ),
    ]
