# Generated by Django 2.2.12 on 2020-07-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200711_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='description_cours',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
