# Generated by Django 2.2.12 on 2020-07-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_siteinfo_description_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='single_cours_description',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='single_cours_titre',
            field=models.CharField(max_length=255, null='True'),
            preserve_default='True',
        ),
    ]
