# Generated by Django 2.2.12 on 2020-07-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20200711_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='single_news_titre',
            field=models.CharField(max_length=255, null='True'),
            preserve_default='True',
        ),
    ]
